_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
action_dim:
    value: 5
alg_name:
    value: soft actor-critic
alpha:
    value: 0.1
auto_entropy_tuning:
    value: true
batch_size:
    value: 256
buffer_size:
    value: 10000
clip_eps:
    value: 0.2
entity:
    value: ""
env_name:
    value: SkittlesEasy
eval_interval:
    value: 10
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
num_episodes:
    value: 1000000
num_updates:
    value: 10000
obs_dim:
    value:
        - 128
        - 128
        - 3
project:
    value: sac
seed:
    value: 42
target_entropy:
    value: 1.5772491541854183
tau:
    value: 0.005
update_epoch:
    value: 4
wandb_mode:
    value: online
warmup_steps:
    value: 1000
